# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gmodstore_sdk
from api.user_badges_api import UserBadgesApi  # noqa: E501
from gmodstore_sdk.rest import ApiException


class TestUserBadgesApi(unittest.TestCase):
    """UserBadgesApi unit test stubs"""

    def setUp(self):
        self.api = api.user_badges_api.UserBadgesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_badge(self):
        """Test case for create_user_badge

        Give a user a badge  # noqa: E501
        """
        pass

    def test_delete_user_badge(self):
        """Test case for delete_user_badge

        Destroy a users's badge  # noqa: E501
        """
        pass

    def test_list_user_badges(self):
        """Test case for list_user_badges

        Fetch all the badges a user has  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
