"""
    gmodstore

    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import gmodstore-sdk
from gmodstore-sdk.api.product_versions_api import ProductVersionsApi  # noqa: E501


class TestProductVersionsApi(unittest.TestCase):
    """ProductVersionsApi unit test stubs"""

    def setUp(self):
        self.api = ProductVersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_product_version(self):
        """Test case for create_product_version

        Create a version for a product  # noqa: E501
        """
        pass

    def test_get_product_download_token(self):
        """Test case for get_product_download_token

        Get a one time use url for downloading a product  # noqa: E501
        """
        pass

    def test_get_product_version(self):
        """Test case for get_product_version

        Show the specified version for a product  # noqa: E501
        """
        pass

    def test_list_product_versions(self):
        """Test case for list_product_versions

        List all versions for a product  # noqa: E501
        """
        pass

    def test_update_product_version(self):
        """Test case for update_product_version

        Update the specified version for a product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
