# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gmodstore_sdk
from models.inline_response2009 import InlineResponse2009  # noqa: E501
from gmodstore_sdk.rest import ApiException


class TestInlineResponse2009(unittest.TestCase):
    """InlineResponse2009 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009(self):
        """Test InlineResponse2009"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gmodstore_sdk.models.inline_response2009.InlineResponse2009()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
