"""
    gmodstore

    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import gmodstore-sdk
from gmodstore-sdk.api.product_reviews_api import ProductReviewsApi  # noqa: E501


class TestProductReviewsApi(unittest.TestCase):
    """ProductReviewsApi unit test stubs"""

    def setUp(self):
        self.api = ProductReviewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_product_review(self):
        """Test case for get_product_review

        Show the specified review for a product  # noqa: E501
        """
        pass

    def test_list_product_reviews(self):
        """Test case for list_product_reviews

        List all reviews for a product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
