# coding: utf-8

"""
    GmodStore API

    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gmodstore-sdk
from gmodstore-sdk.api.permission_groups_api import PermissionGroupsApi  # noqa: E501
from gmodstore-sdk.rest import ApiException


class TestPermissionGroupsApi(unittest.TestCase):
    """PermissionGroupsApi unit test stubs"""

    def setUp(self):
        self.api = gmodstore-sdk.api.permission_groups_api.PermissionGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_permission_groups(self):
        """Test case for get_permission_groups

        Fetches all available permission groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
