"""
    GmodStore API

    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import gmodstore-sdk
from gmodstore-sdk.model.addon_stats import AddonStats
globals()['AddonStats'] = AddonStats
from gmodstore-sdk.model.addon_stats_response import AddonStatsResponse


class TestAddonStatsResponse(unittest.TestCase):
    """AddonStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddonStatsResponse(self):
        """Test AddonStatsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddonStatsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
