# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gmodstore_sdk
from api.addon_coupons_api import AddonCouponsApi  # noqa: E501
from gmodstore_sdk.rest import ApiException


class TestAddonCouponsApi(unittest.TestCase):
    """AddonCouponsApi unit test stubs"""

    def setUp(self):
        self.api = api.addon_coupons_api.AddonCouponsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_addons_addon_id_coupons_coupon_id_delete(self):
        """Test case for addons_addon_id_coupons_coupon_id_delete

        Destroy an addon's coupon  # noqa: E501
        """
        pass

    def test_addons_addon_id_coupons_coupon_id_get(self):
        """Test case for addons_addon_id_coupons_coupon_id_get

        Fetch an addon's coupon  # noqa: E501
        """
        pass

    def test_addons_addon_id_coupons_coupon_id_put(self):
        """Test case for addons_addon_id_coupons_coupon_id_put

        Update an addon's coupon  # noqa: E501
        """
        pass

    def test_addons_addon_id_coupons_get(self):
        """Test case for addons_addon_id_coupons_get

        Fetch all the coupons for an addon  # noqa: E501
        """
        pass

    def test_addons_addon_id_coupons_post(self):
        """Test case for addons_addon_id_coupons_post

        Create an addon coupon  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
