# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gmodstore_sdk
from models.new_addon_coupon import NewAddonCoupon  # noqa: E501
from gmodstore_sdk.rest import ApiException


class TestNewAddonCoupon(unittest.TestCase):
    """NewAddonCoupon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewAddonCoupon(self):
        """Test NewAddonCoupon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gmodstore_sdk.models.new_addon_coupon.NewAddonCoupon()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
