# coding: utf-8

"""
    GmodStore API

    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gmodstore-sdk
from gmodstore-sdk.api.api_key_api import ApiKeyApi  # noqa: E501
from gmodstore-sdk.rest import ApiException


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self):
        self.api = gmodstore-sdk.api.api_key_api.ApiKeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_api_key(self):
        """Test case for get_current_api_key

        Get meta information about the current API key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
