# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gmodstore_sdk
from api.users_api import UsersApi  # noqa: E501
from gmodstore_sdk.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_self_user(self):
        """Test case for get_self_user

        Fetches the current user (API Key Owner)  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Fetch a single user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
