# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gmodstore_sdk
from api.addon_versions_api import AddonVersionsApi  # noqa: E501
from gmodstore_sdk.rest import ApiException


class TestAddonVersionsApi(unittest.TestCase):
    """AddonVersionsApi unit test stubs"""

    def setUp(self):
        self.api = api.addon_versions_api.AddonVersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_addons_addon_id_versions_get(self):
        """Test case for addons_addon_id_versions_get

        Fetch all the versions of an addon  # noqa: E501
        """
        pass

    def test_addons_addon_id_versions_post(self):
        """Test case for addons_addon_id_versions_post

        Create a new version for an addon  # noqa: E501
        """
        pass

    def test_addons_addon_id_versions_version_id_download_get(self):
        """Test case for addons_addon_id_versions_version_id_download_get

        Generate a download token for a specific version of an addon  # noqa: E501
        """
        pass

    def test_addons_addon_id_versions_version_id_get(self):
        """Test case for addons_addon_id_versions_version_id_get

        Fetch a specific version of an addon  # noqa: E501
        """
        pass

    def test_addons_addon_id_versions_version_id_put(self):
        """Test case for addons_addon_id_versions_version_id_put

        Update a version of an addon  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
