# coding: utf-8

"""
    GmodStore

    Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AddonStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'revenue': 'AddonStatsRevenue',
        'views': 'AddonStatsViews',
        'sales': 'AddonStatsSales'
    }

    attribute_map = {
        'revenue': 'revenue',
        'views': 'views',
        'sales': 'sales'
    }

    def __init__(self, revenue=None, views=None, sales=None):  # noqa: E501
        """AddonStats - a model defined in Swagger"""  # noqa: E501
        self._revenue = None
        self._views = None
        self._sales = None
        self.discriminator = None
        if revenue is not None:
            self.revenue = revenue
        if views is not None:
            self.views = views
        if sales is not None:
            self.sales = sales

    @property
    def revenue(self):
        """Gets the revenue of this AddonStats.  # noqa: E501


        :return: The revenue of this AddonStats.  # noqa: E501
        :rtype: AddonStatsRevenue
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue):
        """Sets the revenue of this AddonStats.


        :param revenue: The revenue of this AddonStats.  # noqa: E501
        :type: AddonStatsRevenue
        """

        self._revenue = revenue

    @property
    def views(self):
        """Gets the views of this AddonStats.  # noqa: E501


        :return: The views of this AddonStats.  # noqa: E501
        :rtype: AddonStatsViews
        """
        return self._views

    @views.setter
    def views(self, views):
        """Sets the views of this AddonStats.


        :param views: The views of this AddonStats.  # noqa: E501
        :type: AddonStatsViews
        """

        self._views = views

    @property
    def sales(self):
        """Gets the sales of this AddonStats.  # noqa: E501


        :return: The sales of this AddonStats.  # noqa: E501
        :rtype: AddonStatsSales
        """
        return self._sales

    @sales.setter
    def sales(self, sales):
        """Sets the sales of this AddonStats.


        :param sales: The sales of this AddonStats.  # noqa: E501
        :type: AddonStatsSales
        """

        self._sales = sales

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddonStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddonStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
