# coding: utf-8

"""
    GmodStore

    Welcome to the GmodStore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gmodstore-sdk.configuration import Configuration


class AddonVersion(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'changelog': 'str',
        'file_hash': 'str',
        'file_size': 'int',
        'release_type': 'AddonVersionReleaseType',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'addon': 'Addon'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'changelog': 'changelog',
        'file_hash': 'file_hash',
        'file_size': 'file_size',
        'release_type': 'release_type',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'addon': 'addon'
    }

    def __init__(self, id=None, name=None, changelog=None, file_hash=None, file_size=None, release_type=None, created_at=None, updated_at=None, addon=None, local_vars_configuration=None):  # noqa: E501
        """AddonVersion - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._changelog = None
        self._file_hash = None
        self._file_size = None
        self._release_type = None
        self._created_at = None
        self._updated_at = None
        self._addon = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.changelog = changelog
        if file_hash is not None:
            self.file_hash = file_hash
        if file_size is not None:
            self.file_size = file_size
        if release_type is not None:
            self.release_type = release_type
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if addon is not None:
            self.addon = addon

    @property
    def id(self):
        """Gets the id of this AddonVersion.  # noqa: E501


        :return: The id of this AddonVersion.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AddonVersion.


        :param id: The id of this AddonVersion.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AddonVersion.  # noqa: E501


        :return: The name of this AddonVersion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddonVersion.


        :param name: The name of this AddonVersion.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 80):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `80`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def changelog(self):
        """Gets the changelog of this AddonVersion.  # noqa: E501

        You can pass in markdown here  # noqa: E501

        :return: The changelog of this AddonVersion.  # noqa: E501
        :rtype: str
        """
        return self._changelog

    @changelog.setter
    def changelog(self, changelog):
        """Sets the changelog of this AddonVersion.

        You can pass in markdown here  # noqa: E501

        :param changelog: The changelog of this AddonVersion.  # noqa: E501
        :type changelog: str
        """
        if self.local_vars_configuration.client_side_validation and changelog is None:  # noqa: E501
            raise ValueError("Invalid value for `changelog`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                changelog is not None and len(changelog) > 10000):
            raise ValueError("Invalid value for `changelog`, length must be less than or equal to `10000`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                changelog is not None and len(changelog) < 1):
            raise ValueError("Invalid value for `changelog`, length must be greater than or equal to `1`")  # noqa: E501

        self._changelog = changelog

    @property
    def file_hash(self):
        """Gets the file_hash of this AddonVersion.  # noqa: E501


        :return: The file_hash of this AddonVersion.  # noqa: E501
        :rtype: str
        """
        return self._file_hash

    @file_hash.setter
    def file_hash(self, file_hash):
        """Sets the file_hash of this AddonVersion.


        :param file_hash: The file_hash of this AddonVersion.  # noqa: E501
        :type file_hash: str
        """

        self._file_hash = file_hash

    @property
    def file_size(self):
        """Gets the file_size of this AddonVersion.  # noqa: E501


        :return: The file_size of this AddonVersion.  # noqa: E501
        :rtype: int
        """
        return self._file_size

    @file_size.setter
    def file_size(self, file_size):
        """Sets the file_size of this AddonVersion.


        :param file_size: The file_size of this AddonVersion.  # noqa: E501
        :type file_size: int
        """

        self._file_size = file_size

    @property
    def release_type(self):
        """Gets the release_type of this AddonVersion.  # noqa: E501


        :return: The release_type of this AddonVersion.  # noqa: E501
        :rtype: AddonVersionReleaseType
        """
        return self._release_type

    @release_type.setter
    def release_type(self, release_type):
        """Sets the release_type of this AddonVersion.


        :param release_type: The release_type of this AddonVersion.  # noqa: E501
        :type release_type: AddonVersionReleaseType
        """

        self._release_type = release_type

    @property
    def created_at(self):
        """Gets the created_at of this AddonVersion.  # noqa: E501


        :return: The created_at of this AddonVersion.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AddonVersion.


        :param created_at: The created_at of this AddonVersion.  # noqa: E501
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this AddonVersion.  # noqa: E501


        :return: The updated_at of this AddonVersion.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AddonVersion.


        :param updated_at: The updated_at of this AddonVersion.  # noqa: E501
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def addon(self):
        """Gets the addon of this AddonVersion.  # noqa: E501


        :return: The addon of this AddonVersion.  # noqa: E501
        :rtype: Addon
        """
        return self._addon

    @addon.setter
    def addon(self, addon):
        """Sets the addon of this AddonVersion.


        :param addon: The addon of this AddonVersion.  # noqa: E501
        :type addon: Addon
        """

        self._addon = addon

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddonVersion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AddonVersion):
            return True

        return self.to_dict() != other.to_dict()
