# coding: utf-8

"""
    GmodStore

    Welcome to the GmodStore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gmodstore-sdk.configuration import Configuration


class TeamUser(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'team_id': 'int',
        'primary': 'bool',
        'user': 'User'
    }

    attribute_map = {
        'team_id': 'team_id',
        'primary': 'primary',
        'user': 'user'
    }

    def __init__(self, team_id=None, primary=None, user=None, local_vars_configuration=None):  # noqa: E501
        """TeamUser - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._team_id = None
        self._primary = None
        self._user = None
        self.discriminator = None

        if team_id is not None:
            self.team_id = team_id
        if primary is not None:
            self.primary = primary
        if user is not None:
            self.user = user

    @property
    def team_id(self):
        """Gets the team_id of this TeamUser.  # noqa: E501


        :return: The team_id of this TeamUser.  # noqa: E501
        :rtype: int
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this TeamUser.


        :param team_id: The team_id of this TeamUser.  # noqa: E501
        :type team_id: int
        """

        self._team_id = team_id

    @property
    def primary(self):
        """Gets the primary of this TeamUser.  # noqa: E501


        :return: The primary of this TeamUser.  # noqa: E501
        :rtype: bool
        """
        return self._primary

    @primary.setter
    def primary(self, primary):
        """Sets the primary of this TeamUser.


        :param primary: The primary of this TeamUser.  # noqa: E501
        :type primary: bool
        """

        self._primary = primary

    @property
    def user(self):
        """Gets the user of this TeamUser.  # noqa: E501


        :return: The user of this TeamUser.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this TeamUser.


        :param user: The user of this TeamUser.  # noqa: E501
        :type user: User
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamUser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TeamUser):
            return True

        return self.to_dict() != other.to_dict()
