"""
    GmodStore API

    Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from gmodstore-sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from gmodstore-sdk.exceptions import ApiAttributeError


def lazy_import():
    from gmodstore-sdk.model.addon_images import AddonImages
    from gmodstore-sdk.model.addon_price import AddonPrice
    from gmodstore-sdk.model.addon_stats import AddonStats
    from gmodstore-sdk.model.addon_version import AddonVersion
    from gmodstore-sdk.model.team import Team
    globals()['AddonImages'] = AddonImages
    globals()['AddonPrice'] = AddonPrice
    globals()['AddonStats'] = AddonStats
    globals()['AddonVersion'] = AddonVersion
    globals()['Team'] = Team


class Addon(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (int,),  # noqa: E501
            'active': (bool,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'short_description': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'requirements': ([str],),  # noqa: E501
            'price': (AddonPrice,),  # noqa: E501
            'images': (AddonImages,),  # noqa: E501
            'views': (int,),  # noqa: E501
            'rating_avg': (str,),  # noqa: E501
            'rating_count': (int,),  # noqa: E501
            'purchases_count': (int,),  # noqa: E501
            'dependent_addon': (int, none_type,),  # noqa: E501
            'has_drm': (bool,),  # noqa: E501
            'requires_chromium': (bool,),  # noqa: E501
            'slug': (str,),  # noqa: E501
            'route': (str,),  # noqa: E501
            'created_at': (datetime,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'latest_version': (AddonVersion,),  # noqa: E501
            'team': (Team,),  # noqa: E501
            'stats': (AddonStats,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'active': 'active',  # noqa: E501
        'name': 'name',  # noqa: E501
        'short_description': 'short_description',  # noqa: E501
        'description': 'description',  # noqa: E501
        'requirements': 'requirements',  # noqa: E501
        'price': 'price',  # noqa: E501
        'images': 'images',  # noqa: E501
        'views': 'views',  # noqa: E501
        'rating_avg': 'rating_avg',  # noqa: E501
        'rating_count': 'rating_count',  # noqa: E501
        'purchases_count': 'purchases_count',  # noqa: E501
        'dependent_addon': 'dependent_addon',  # noqa: E501
        'has_drm': 'has_drm',  # noqa: E501
        'requires_chromium': 'requires_chromium',  # noqa: E501
        'slug': 'slug',  # noqa: E501
        'route': 'route',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'latest_version': 'latest_version',  # noqa: E501
        'team': 'team',  # noqa: E501
        'stats': 'stats',  # noqa: E501
    }

    read_only_vars = {
        'views',  # noqa: E501
        'rating_avg',  # noqa: E501
        'rating_count',  # noqa: E501
        'purchases_count',  # noqa: E501
        'dependent_addon',  # noqa: E501
        'has_drm',  # noqa: E501
        'requires_chromium',  # noqa: E501
        'slug',  # noqa: E501
        'route',  # noqa: E501
        'created_at',  # noqa: E501
        'updated_at',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Addon - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int): [optional]  # noqa: E501
            active (bool): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            short_description (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            requirements ([str]): [optional]  # noqa: E501
            price (AddonPrice): [optional]  # noqa: E501
            images (AddonImages): [optional]  # noqa: E501
            views (int): [optional]  # noqa: E501
            rating_avg (str): [optional]  # noqa: E501
            rating_count (int): [optional]  # noqa: E501
            purchases_count (int): [optional]  # noqa: E501
            dependent_addon (int, none_type): [optional]  # noqa: E501
            has_drm (bool): [optional]  # noqa: E501
            requires_chromium (bool): [optional]  # noqa: E501
            slug (str): [optional]  # noqa: E501
            route (str): [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
            latest_version (AddonVersion): [optional]  # noqa: E501
            team (Team): [optional]  # noqa: E501
            stats (AddonStats): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Addon - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int): [optional]  # noqa: E501
            active (bool): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            short_description (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            requirements ([str]): [optional]  # noqa: E501
            price (AddonPrice): [optional]  # noqa: E501
            images (AddonImages): [optional]  # noqa: E501
            views (int): [optional]  # noqa: E501
            rating_avg (str): [optional]  # noqa: E501
            rating_count (int): [optional]  # noqa: E501
            purchases_count (int): [optional]  # noqa: E501
            dependent_addon (int, none_type): [optional]  # noqa: E501
            has_drm (bool): [optional]  # noqa: E501
            requires_chromium (bool): [optional]  # noqa: E501
            slug (str): [optional]  # noqa: E501
            route (str): [optional]  # noqa: E501
            created_at (datetime): [optional]  # noqa: E501
            updated_at (datetime): [optional]  # noqa: E501
            latest_version (AddonVersion): [optional]  # noqa: E501
            team (Team): [optional]  # noqa: E501
            stats (AddonStats): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
